### PR TITLE
Merge OpenSSL implementation into Seastar v24.2.x

### PR DESCRIPTION
**Pull request by michael-redpanda**
This PR will merge the OpenSSL feature branch into v24.2.x.

* Adds OpenSSL support
* Adds new APIs for setting cipher strings/suites/server preference into the credentials API
* Adds options for using OpenSSL instead of GnuTLS

Note:

This is the same code that has been reviewed and merged into [OpenSSL feature branch](https://github.com/redpanda-data/seastar/tree/rebase-feature-ossl).  This is a refactoring of the history to make upstreaming easier.

### CODE REVIEW

**Review by graphcareful — DISMISSED** [review]

**Review by BenPope — COMMENTED** [review]
> This is a refactoring of the history to make upstreaming easier.

I know this is just a refactoring of the history but it seems like an opportune moment to address:

1. There are at least 3 compilation errors with g++ 11.
2. Is there a way to run the test suite?
3. Can a couple of OpenSSL builds be added to the test suite?
4. Have we ensured the modules build works?
5. Some includes are `"net/*"` instead of `<seastar/net/*>`

**Comment by michael-redpanda** [comment]
> 1. There are at least 3 compilation errors with g++ 11.

Maybe we can address them when we upstream?  We are getting down to the wire here and I need to get this running with Redpanda

> 2. Is there a way to run the test suite?

you mean as part of CI in _this_ repo?

> 3. Can a couple of OpenSSL builds be added to the test suite?

Similar quesiton to #2

> 4. Have we ensured the modules build works?

I think we can address this when we upstream it

> 5. Some includes are "net/*" instead of <seastar/net/*>

I agree this should be fixed

**Comment by michael-redpanda** [comment]
https://github.com/redpanda-data/seastar/pull/120

**Comment by BenPope** [comment]
> > 1. There are at least 3 compilation errors with g++ 11.
> 
> Maybe we can address them when we upstream? We are getting down to the wire here and I need to get this running with Redpanda

#120 accepted!

> > 2. Is there a way to run the test suite?
> 
> you mean as part of CI in _this_ repo?

Yes.

> > 3. Can a couple of OpenSSL builds be added to the test suite?
> 
> Similar quesiton to 2

Similar answer.

> > 4. Have we ensured the modules build works?
> 
> I think we can address this when we upstream it

I'm ok with that.

> > 5. Some includes are "net/_" instead of <seastar/net/_>
> 
> I agree this should be fixed

It's not wrong.

**Comment by michael-redpanda** [comment]
Force push `baf82c0`:

* fixes from #120

**Review by graphcareful — APPROVED** [review]

**Pull request merged**
