### PR TITLE
Rebase our changes on upstream for v23.3.x

### PR DESCRIPTION
**Pull request by BenPope**
Related PRs:
* https://github.com/redpanda-data/vtools/pull/2003
* https://github.com/redpanda-data/redpanda/pull/12658

### CODE REVIEW

**Comment by StephanDollberg** [comment]
Many thanks for doing this.

I looked at the memory related changes and they look fine. I can't see any changes really, did you have to do much conflict resolution?

How are you actually building this?

I am using the following (works for 23.2):

```
./configure.py --mode=release --compiler ~/build/redpanda/vbuild/llvm/build/bin/clang++ --c-compiler ~/build/redpanda/vbuild/llvm/build/bin/clang --c++-standard=20 --compile-commands-json --heap-profiling
```

but get a failed build:

```
/home/stephan/build/seastar/tests/perf/shared_token_bucket.cc:227:22: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
        return work([this] (std::chrono::duration<double> d) {
```

This also seems broken in upstream seastar though.

**Comment by BenPope** [comment]
> I looked at the memory related changes and they look fine. I can't see any changes really, did you have to do much conflict resolution?

I don't recall much in the way of conflicts for that stuff.

> How are you actually building this?

You can follow along on the vtools PR https://github.com/redpanda-data/vtools/pull/2003

**Comment by StephanDollberg** [comment]
Ah I see now there is already https://github.com/scylladb/seastar/pull/1775 for the build failures

**Comment by dotnwat** [comment]
@BenPope @StephanDollberg do we really have 2600 LOC that aren't in upstream Seastar, or is something else going on with the way that the PR is constructed?

**Comment by StephanDollberg** [comment]
Think that number is correct though it might sound worse than it is. We do seem to have added lots of tests and perf tests as well. 

Memory and cpu profiler are a part of that. We don't have lots of experience with them yet but I think at the same we know that nothing should be fundamentally wrong with them so we should be in a good position to start the upstreaming process now. 

The metrics/prometheus side feels like the other bigger change. Not sure what the plan is for that.

**Review by dotnwat — APPROVED** [review]

**Pull request merged**
